[package]
name = "app-core"
version = "0.1.0"
edition = "2021"
rust-version = "1.82.0"

[dependencies]
chrono = { version = "0.4.31", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_with = "3.5.1"
serde_json = "1"
app-macros = { path = "../app-macros" }